### PR TITLE
Introduce geb integration tests

### LINKED ISSUE #66: All selenium tests are failing
Disregard the horrible fact that the selenium tests of this addon need the started [osiam integration tests](https://github.com/osiam/connector4java-integration-tests), all selenium tests are failing because they are trying to access html elements which are not present in the current html templates. Example exception message:
`org.openqa.selenium.NoSuchElementException: Unable to locate a node using //form[@id = 'confirmation-form']/button`

### PR DESCRIPTION
**Pull request by dacrome**
- Delete selenium tests and use http://www.gebish.org/ instead
- Introduce two test classes
  - CreateUserIT: After successful 3-legged OAuth flow login and
                  redirect back to the user list, create a new
                  user
  - LoginIT: Test the 3-legged OAuth flow
- Introduce docker for the test infrastructure to run the
  administration and osiam within a tomcat docker container

Resolves #66

### CODE REVIEW

**Comment by tkrille** [comment]
Looks good to me, but please, fix the commit message.

**Comment by dacrome** [comment]
Done

**Comment by tkrille** [comment]
I don't see any changes. What about the stuff from codacy?

**Comment by dacrome** [comment]
I changed the commit message body but not the commit message itself. But now it's changed and also the PR title.

**Comment by dacrome** [comment]
Updated

**Comment by dacrome** [comment]
Blocked by #126

**Comment by tkrille** [comment]
You can rebase now. Tell me when you're ready.

**Comment by dacrome** [comment]
Updated and rebased.

**Comment by tkrille** [comment]
Cool, thanks!

**Pull request merged**
