### PR TITLE
[change] use the slf4j interface to get the loggers

### PR DESCRIPTION
**Pull request by woglinde**
Fixes: #80

### CODE REVIEW

**Comment by dacrome** [comment]
Thanks! I think with a later pull request, the [log levels](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-custom-log-levels) should be configured in the [example deploy properties file](https://github.com/osiam/addon-administration/blob/master/src/main/deploy/addon-administration.properties)

**Comment by wallner** [comment]
Somehow this fell off the truck. Sorry.

**Comment by wallner** [comment]
Can you please rebase this PR

**Comment by tkrille** [comment]
@woglinde Please, rebase your PR so we can merge it. Thanks!

**Comment by tkrille** [comment]
Thanks!

**Pull request merged**
