### PR TITLE
Fix handling of boolean extension fields

### LINKED ISSUE #83: After initial registration in OSIAM, boolean values are shown as 'true' although they are 'false'
After the initial registration in OSIAM the 'edit User' view is shown. All checkboxes are marked as 'true' but the boolean values are not stored in the database. If I uncheck these boxes and activate 'save' the boolean values are still shown as 'true' after reloading.

### PR DESCRIPTION
**Pull request by tkrille**
Fixes #83

### CODE REVIEW

**Comment by tkrille** [comment]
Stop. I've found a mistake. I will update the PR this evening.

**Comment by tkrille** [comment]
Sorry, I couldn't make it yesterday. I'll try again today in the evening.

**Comment by dacrome** [comment]
No problem. Am I right that I need to create an extension with a boolean type in the resource-servers database to test this? And of course I use the [OSIAM docker-image](https://github.com/osiam/docker-image) and replace the addon-administration war

**Comment by tkrille** [comment]
Yes, you're right. That's exactly the way I've tested it.

**Comment by tkrille** [comment]
Updated. Now it should work correctly. The problem with the former version was, that when setting the `BOOLEAN` field to `false`, the value of the checkbox also is false. This way, if checked, then the field's value becomes `false`. This is not the intended behavior. By constantly setting the value attribute to `true`, if checked, the field's value becomes `true`. Unchecking leads to the complete removal of the field's value, i.e. the row in the the database will be removed.

**Comment by tkrille** [comment]
@dacrome Did you manage to take a look at this again?

**Comment by dacrome** [comment]
@tkrille No, but I think today or tomorrow.

**Comment by dacrome** [comment]
Works like a charm. Thank you!

**Pull request merged**
